require("data.group")
require("data.fruit")
require("data.vegetable")
require("data.animal_products")
require("data.item")
require("data.plant")
require("data.recipe")
require("data.technology")
require("data.entity")
require("data.juice")

